-- Migration: CID-10 completo para ARSen
-- Popula a tabela cid10_codes com cobertura ampla

-- Limpar duplicatas antes de inserir
DELETE FROM cid10_codes WHERE code IN (
  SELECT code FROM cid10_codes GROUP BY code HAVING COUNT(*) > 1
);

INSERT INTO cid10_codes (code, description, category) VALUES
-- ══ CAPÍTULO I — Doenças infecciosas e parasitárias (A00–B99) ══
('A00','Cólera','Doenças infecciosas'),('A01','Febres tifóide e paratifóide','Doenças infecciosas'),
('A02','Outras infecções por Salmonella','Doenças infecciosas'),('A03','Shiguelose','Doenças infecciosas'),
('A04','Outras infecções intestinais bacterianas','Doenças infecciosas'),
('A05','Outras intoxicações alimentares bacterianas','Doenças infecciosas'),
('A06','Amebíase','Doenças infecciosas'),('A07','Outras doenças intestinais por protozoários','Doenças infecciosas'),
('A08','Infecções intestinais virais','Doenças infecciosas'),
('A09','Diarreia e gastroenterite de origem infecciosa presumível','Doenças infecciosas'),
('A15','Tuberculose respiratória','Doenças infecciosas'),('A16','Tuberculose respiratória sem confirmação bacteriológica','Doenças infecciosas'),
('A17','Tuberculose do sistema nervoso','Doenças infecciosas'),('A18','Tuberculose de outros órgãos','Doenças infecciosas'),
('A19','Tuberculose miliar','Doenças infecciosas'),
('A20','Peste','Doenças infecciosas'),('A21','Tularemia','Doenças infecciosas'),
('A22','Carbúnculo','Doenças infecciosas'),('A23','Brucelose','Doenças infecciosas'),
('A24','Mormo e melioidose','Doenças infecciosas'),('A25','Febres transmitidas por mordedura de rato','Doenças infecciosas'),
('A26','Erisipelóide','Doenças infecciosas'),('A27','Leptospirose','Doenças infecciosas'),
('A28','Outras zoonoses bacterianas','Doenças infecciosas'),
('A30','Hanseníase (lepra)','Doenças infecciosas'),('A31','Infecções por outras micobactérias','Doenças infecciosas'),
('A32','Listeriose','Doenças infecciosas'),('A33','Tétano neonatal','Doenças infecciosas'),
('A34','Tétano obstétrico','Doenças infecciosas'),('A35','Outros tipos de tétano','Doenças infecciosas'),
('A36','Difteria','Doenças infecciosas'),('A37','Coqueluche','Doenças infecciosas'),
('A38','Escarlatina','Doenças infecciosas'),('A39','Infecção meningocócica','Doenças infecciosas'),
('A40','Septicemia por Streptococcus','Doenças infecciosas'),('A41','Outras septicemias','Doenças infecciosas'),
('A41.0','Sepse por Staphylococcus aureus','Doenças infecciosas'),
('A41.1','Sepse por outros Staphylococcus','Doenças infecciosas'),
('A41.2','Sepse por Streptococcus não especificado','Doenças infecciosas'),
('A41.3','Sepse por Haemophilus influenzae','Doenças infecciosas'),
('A41.4','Sepse por anaeróbios','Doenças infecciosas'),
('A41.5','Sepse por outros Gram-negativos','Doenças infecciosas'),
('A41.50','Sepse por Escherichia coli','Doenças infecciosas'),
('A41.51','Sepse por Pseudomonas','Doenças infecciosas'),
('A41.52','Sepse por Klebsiella','Doenças infecciosas'),
('A41.8','Outras sepses especificadas','Doenças infecciosas'),
('A41.9','Sepse não especificada','Doenças infecciosas'),
('A42','Actinomicose','Doenças infecciosas'),('A43','Nocardiose','Doenças infecciosas'),
('A44','Bartonelose','Doenças infecciosas'),('A46','Erisipela','Doenças infecciosas'),
('A48','Outras doenças bacterianas','Doenças infecciosas'),('A49','Infecção bacteriana de localização não especificada','Doenças infecciosas'),
('A50','Sífilis congênita','Doenças infecciosas'),('A51','Sífilis precoce','Doenças infecciosas'),
('A52','Sífilis tardia','Doenças infecciosas'),('A53','Outras formas e sífilis não especificada','Doenças infecciosas'),
('A54','Infecção gonocócica','Doenças infecciosas'),('A55','Linfogranuloma por clamídia','Doenças infecciosas'),
('A56','Outras infecções por clamídias','Doenças infecciosas'),('A57','Cancro mole','Doenças infecciosas'),
('A58','Granuloma inguinal','Doenças infecciosas'),('A59','Tricomoníase','Doenças infecciosas'),
('A60','Infecção anogenital pelo vírus do herpes','Doenças infecciosas'),
('A63','Outras doenças sexualmente transmitidas','Doenças infecciosas'),
('A64','Doença sexualmente transmitida não especificada','Doenças infecciosas'),
('A65','Sífilis não venérea','Doenças infecciosas'),('A66','Bouba','Doenças infecciosas'),
('A67','Pinta','Doenças infecciosas'),('A68','Febres recorrentes','Doenças infecciosas'),
('A69','Outras infecções por espiroquetas','Doenças infecciosas'),
('A70','Infecção por Chlamydia psittaci','Doenças infecciosas'),
('A71','Tracoma','Doenças infecciosas'),('A74','Outras doenças causadas por clamídias','Doenças infecciosas'),
('A75','Tifo epidêmico','Doenças infecciosas'),('A77','Febre maculosa (febre do carrapato)','Doenças infecciosas'),
('A78','Febre Q','Doenças infecciosas'),('A79','Outras riquetsioses','Doenças infecciosas'),
('A80','Poliomielite aguda','Doenças infecciosas'),('A81','Infecções por vírus lentos do sistema nervoso central','Doenças infecciosas'),
('A82','Raiva','Doenças infecciosas'),('A83','Encefalite viral transmitida por mosquito','Doenças infecciosas'),
('A84','Encefalite viral transmitida por carrapato','Doenças infecciosas'),
('A85','Outras encefalites virais','Doenças infecciosas'),
('A86','Encefalite viral não especificada','Doenças infecciosas'),
('A87','Meningite viral','Doenças infecciosas'),('A88','Outras infecções virais do SNC','Doenças infecciosas'),
('A89','Infecção viral não especificada do SNC','Doenças infecciosas'),
('A90','Dengue clássica','Doenças infecciosas'),('A91','Febre hemorrágica devida ao vírus dengue','Doenças infecciosas'),
('A92','Outras febres virais transmitidas por mosquitos','Doenças infecciosas'),
('A93','Outras febres virais transmitidas por artrópodes','Doenças infecciosas'),
('A94','Febre viral transmitida por artrópode não especificada','Doenças infecciosas'),
('A95','Febre amarela','Doenças infecciosas'),('A96','Febres hemorrágicas por arenavírus','Doenças infecciosas'),
('A98','Outras febres hemorrágicas virais','Doenças infecciosas'),('A99','Febre hemorrágica viral não especificada','Doenças infecciosas'),
('B00','Infecções pelo vírus do herpes simplex','Doenças infecciosas'),
('B01','Varicela','Doenças infecciosas'),('B02','Herpes zoster','Doenças infecciosas'),
('B03','Varíola','Doenças infecciosas'),('B04','Infecção pelo vírus monkeypox','Doenças infecciosas'),
('B05','Sarampo','Doenças infecciosas'),('B06','Rubéola','Doenças infecciosas'),
('B07','Verrugas de origem viral','Doenças infecciosas'),('B08','Outras infecções virais com lesões cutâneas','Doenças infecciosas'),
('B09','Infecção viral não especificada com lesão cutânea','Doenças infecciosas'),
('B15','Hepatite aguda A','Doenças infecciosas'),('B16','Hepatite aguda B','Doenças infecciosas'),
('B17','Outras hepatites virais agudas','Doenças infecciosas'),('B18','Hepatite viral crônica','Doenças infecciosas'),
('B19','Hepatite viral não especificada','Doenças infecciosas'),
('B20','Doença por vírus da imunodeficiência humana (HIV) resultando em doenças infecciosas e parasitárias','HIV/AIDS'),
('B21','Doença por HIV resultando em neoplasias malignas','HIV/AIDS'),
('B22','Doença por HIV resultando em outras doenças especificadas','HIV/AIDS'),
('B23','Doença por HIV resultando em outras condições','HIV/AIDS'),
('B24','Doença por HIV não especificada','HIV/AIDS'),
('B25','Doença por citomegalovírus','Doenças infecciosas'),('B26','Parotidite epidêmica','Doenças infecciosas'),
('B27','Mononucleose infecciosa','Doenças infecciosas'),('B30','Conjuntivite viral','Doenças infecciosas'),
('B33','Outras doenças virais','Doenças infecciosas'),('B34','Doença viral de localização não especificada','Doenças infecciosas'),
('B35','Dermatofitose','Doenças infecciosas'),('B36','Outras micoses superficiais','Doenças infecciosas'),
('B37','Candidiose','Doenças infecciosas'),('B38','Coccidioidomicose','Doenças infecciosas'),
('B39','Histoplasmose','Doenças infecciosas'),('B40','Blastomicose','Doenças infecciosas'),
('B41','Paracoccidioidomicose','Doenças infecciosas'),('B42','Esporotricose','Doenças infecciosas'),
('B43','Cromomicose e abscesso feomicotico','Doenças infecciosas'),('B44','Aspergilose','Doenças infecciosas'),
('B45','Criptococose','Doenças infecciosas'),('B46','Zigomicose','Doenças infecciosas'),
('B47','Micetoma','Doenças infecciosas'),('B48','Outras micoses','Doenças infecciosas'),
('B49','Micose não especificada','Doenças infecciosas'),
('B50','Malária por Plasmodium falciparum','Doenças infecciosas'),('B51','Malária por Plasmodium vivax','Doenças infecciosas'),
('B52','Malária por Plasmodium malariae','Doenças infecciosas'),('B53','Outras formas de malária','Doenças infecciosas'),
('B54','Malária não especificada','Doenças infecciosas'),('B55','Leishmaniose','Doenças infecciosas'),
('B56','Tripanossomíase africana','Doenças infecciosas'),('B57','Doença de Chagas','Doenças infecciosas'),
('B58','Toxoplasmose','Doenças infecciosas'),('B59','Pneumocistose','Doenças infecciosas'),
('B60','Outras doenças por protozoários','Doenças infecciosas'),('B64','Doença por protozoário não especificada','Doenças infecciosas'),
('B65','Esquistossomose','Doenças infecciosas'),('B66','Outras infestações por trematóides','Doenças infecciosas'),
('B67','Equinococose','Doenças infecciosas'),('B68','Teníase','Doenças infecciosas'),
('B69','Cisticercose','Doenças infecciosas'),('B70','Difilobotríase e esparganose','Doenças infecciosas'),
('B71','Outras infestações por cestóides','Doenças infecciosas'),('B72','Dracontíase','Doenças infecciosas'),
('B73','Oncocercose','Doenças infecciosas'),('B74','Filariose','Doenças infecciosas'),
('B75','Triquinose','Doenças infecciosas'),('B76','Ancilostomíase','Doenças infecciosas'),
('B77','Ascaridíase','Doenças infecciosas'),('B78','Estrongiloidíase','Doenças infecciosas'),
('B79','Tricuríase','Doenças infecciosas'),('B80','Enterobíase','Doenças infecciosas'),
('B81','Outras helmintíases intestinais','Doenças infecciosas'),('B82','Parasitose intestinal não especificada','Doenças infecciosas'),
('B83','Outras helmintíases','Doenças infecciosas'),('B85','Pediculose e ftiríase','Doenças infecciosas'),
('B86','Escabiose','Doenças infecciosas'),('B87','Miíase','Doenças infecciosas'),
('B88','Outras infestações','Doenças infecciosas'),('B89','Doença parasitária não especificada','Doenças infecciosas'),
('B90','Sequelas de tuberculose','Doenças infecciosas'),('B91','Sequelas de poliomielite','Doenças infecciosas'),
('B92','Sequelas de hanseníase','Doenças infecciosas'),('B94','Sequelas de outras doenças infecciosas','Doenças infecciosas'),
('B95','Estreptococos e estafilococos como causa de doenças','Doenças infecciosas'),
('B96','Outros agentes bacterianos como causa de doenças','Doenças infecciosas'),
('B97','Vírus como causa de doenças','Doenças infecciosas'),('B99','Outras doenças infecciosas','Doenças infecciosas'),
-- ══ CAPÍTULO II — Neoplasias (C00–D48) ══
('C00','Neoplasia maligna do lábio','Neoplasias'),('C01','Neoplasia maligna da base da língua','Neoplasias'),
('C02','Neoplasia maligna de outras partes da língua','Neoplasias'),
('C03','Neoplasia maligna da gengiva','Neoplasias'),('C04','Neoplasia maligna do assoalho da boca','Neoplasias'),
('C05','Neoplasia maligna do palato','Neoplasias'),('C06','Neoplasia maligna de outras partes da boca','Neoplasias'),
('C07','Neoplasia maligna da glândula parótida','Neoplasias'),
('C08','Neoplasia maligna de outras glândulas salivares','Neoplasias'),
('C09','Neoplasia maligna da amígdala','Neoplasias'),('C10','Neoplasia maligna da orofaringe','Neoplasias'),
('C11','Neoplasia maligna da nasofaringe','Neoplasias'),('C12','Neoplasia maligna do seio piriforme','Neoplasias'),
('C13','Neoplasia maligna da hipofaringe','Neoplasias'),('C14','Neoplasia maligna de outros locais do lábio, cavidade oral e faringe','Neoplasias'),
('C15','Neoplasia maligna do esôfago','Neoplasias'),('C16','Neoplasia maligna do estômago','Neoplasias'),
('C17','Neoplasia maligna do intestino delgado','Neoplasias'),('C18','Neoplasia maligna do cólon','Neoplasias'),
('C19','Neoplasia maligna da junção retossigmóide','Neoplasias'),('C20','Neoplasia maligna do reto','Neoplasias'),
('C21','Neoplasia maligna do ânus e do canal anal','Neoplasias'),('C22','Neoplasia maligna do fígado','Neoplasias'),
('C23','Neoplasia maligna da vesícula biliar','Neoplasias'),('C24','Neoplasia maligna de outras partes das vias biliares','Neoplasias'),
('C25','Neoplasia maligna do pâncreas','Neoplasias'),('C26','Neoplasia maligna de outros órgãos digestivos','Neoplasias'),
('C30','Neoplasia maligna da fossa nasal e do ouvido médio','Neoplasias'),
('C31','Neoplasia maligna dos seios da face','Neoplasias'),
('C32','Neoplasia maligna da laringe','Neoplasias'),('C33','Neoplasia maligna da traqueia','Neoplasias'),
('C34','Neoplasia maligna dos brônquios e dos pulmões','Neoplasias'),
('C37','Neoplasia maligna do timo','Neoplasias'),('C38','Neoplasia maligna do coração, mediastino e pleura','Neoplasias'),
('C39','Neoplasia maligna de outros órgãos respiratórios','Neoplasias'),
('C40','Neoplasia maligna dos ossos dos membros','Neoplasias'),
('C41','Neoplasia maligna dos ossos de outras localizações','Neoplasias'),
('C43','Melanoma maligno da pele','Neoplasias'),('C44','Outras neoplasias malignas da pele','Neoplasias'),
('C45','Mesotelioma','Neoplasias'),('C46','Sarcoma de Kaposi','Neoplasias'),
('C47','Neoplasia maligna dos nervos periféricos','Neoplasias'),
('C48','Neoplasia maligna do retroperitônio e do peritônio','Neoplasias'),
('C49','Neoplasia maligna de outros tecidos conjuntivos','Neoplasias'),
('C50','Neoplasia maligna da mama','Neoplasias'),('C51','Neoplasia maligna da vulva','Neoplasias'),
('C52','Neoplasia maligna da vagina','Neoplasias'),('C53','Neoplasia maligna do colo do útero','Neoplasias'),
('C54','Neoplasia maligna do corpo do útero','Neoplasias'),('C55','Neoplasia maligna do útero','Neoplasias'),
('C56','Neoplasia maligna do ovário','Neoplasias'),('C57','Neoplasia maligna de outros órgãos genitais femininos','Neoplasias'),
('C58','Neoplasia maligna da placenta','Neoplasias'),('C60','Neoplasia maligna do pênis','Neoplasias'),
('C61','Neoplasia maligna da próstata','Neoplasias'),('C62','Neoplasia maligna dos testículos','Neoplasias'),
('C63','Neoplasia maligna de outros órgãos genitais masculinos','Neoplasias'),
('C64','Neoplasia maligna do rim','Neoplasias'),('C65','Neoplasia maligna da pelve renal','Neoplasias'),
('C66','Neoplasia maligna do ureter','Neoplasias'),('C67','Neoplasia maligna da bexiga','Neoplasias'),
('C68','Neoplasia maligna de outros órgãos urinários','Neoplasias'),
('C69','Neoplasia maligna do olho','Neoplasias'),('C70','Neoplasia maligna das meninges','Neoplasias'),
('C71','Neoplasia maligna do encéfalo','Neoplasias'),('C72','Neoplasia maligna da medula espinhal','Neoplasias'),
('C73','Neoplasia maligna da glândula tireoide','Neoplasias'),
('C74','Neoplasia maligna da glândula suprarrenal','Neoplasias'),
('C75','Neoplasia maligna de outras glândulas endócrinas','Neoplasias'),
('C76','Neoplasia maligna de outras localizações','Neoplasias'),
('C77','Neoplasia maligna secundária dos gânglios linfáticos','Neoplasias'),
('C78','Neoplasia maligna secundária dos órgãos respiratórios','Neoplasias'),
('C79','Neoplasia maligna secundária de outros locais','Neoplasias'),
('C80','Neoplasia maligna sem especificação de localização','Neoplasias'),
('C81','Doença de Hodgkin','Neoplasias'),('C82','Linfoma não Hodgkin folicular','Neoplasias'),
('C83','Linfoma não Hodgkin difuso','Neoplasias'),('C84','Linfomas T e NK maduros','Neoplasias'),
('C85','Outros linfomas não Hodgkin','Neoplasias'),('C88','Doenças imunoproliferativas malignas','Neoplasias'),
('C90','Mieloma múltiplo','Neoplasias'),('C91','Leucemia linfóide','Neoplasias'),
('C92','Leucemia mieloide','Neoplasias'),('C93','Leucemia monocítica','Neoplasias'),
('C94','Outras leucemias','Neoplasias'),('C95','Leucemia de tipo celular não especificado','Neoplasias'),
('C96','Outras neoplasias malignas do tecido linfático','Neoplasias'),
('C97','Neoplasias malignas de localizações múltiplas independentes','Neoplasias'),
-- ══ CAPÍTULO III — Doenças do sangue (D50–D89) ══
('D50','Anemia por deficiência de ferro','Sangue'),('D51','Anemia por deficiência de vitamina B12','Sangue'),
('D52','Anemia por deficiência de folato','Sangue'),('D53','Outras anemias nutricionais','Sangue'),
('D55','Anemia devida a transtornos enzimáticos','Sangue'),('D56','Talassemia','Sangue'),
('D57','Transtornos falciformes','Sangue'),('D58','Outras anemias hemolíticas hereditárias','Sangue'),
('D59','Anemia hemolítica adquirida','Sangue'),('D60','Aplasia eritróide adquirida','Sangue'),
('D61','Outras anemias aplásticas','Sangue'),('D62','Anemia aguda pós-hemorrágica','Sangue'),
('D63','Anemia em doenças crônicas','Sangue'),('D64','Outras anemias','Sangue'),
('D65','Coagulação intravascular disseminada','Sangue'),('D66','Deficiência hereditária do fator VIII','Sangue'),
('D67','Deficiência hereditária do fator IX','Sangue'),('D68','Outros defeitos da coagulação','Sangue'),
('D69','Púrpura e outras afecções hemorrágicas','Sangue'),('D70','Agranulocitose','Sangue'),
('D71','Transtornos funcionais dos neutrófilos','Sangue'),('D72','Outros transtornos dos leucócitos','Sangue'),
('D73','Doenças do baço','Sangue'),('D74','Metemoglobinemia','Sangue'),
('D75','Outras doenças do sangue','Sangue'),('D76','Histiocitose','Sangue'),
('D77','Outros transtornos do sangue','Sangue'),
('D80','Imunodeficiência com predominância de deficiência de anticorpos','Imunologia'),
('D81','Imunodeficiências combinadas','Imunologia'),('D82','Imunodeficiências associadas a outros defeitos','Imunologia'),
('D83','Imunodeficiência variável comum','Imunologia'),('D84','Outras imunodeficiências','Imunologia'),
('D86','Sarcoidose','Imunologia'),('D89','Outros transtornos imunitários','Imunologia'),
-- ══ CAPÍTULO IV — Doenças endócrinas e metabólicas (E00–E90) ══
('E00','Síndrome de deficiência congênita de iodo','Endócrino/Metabólico'),
('E01','Transtornos da tireoide por deficiência de iodo','Endócrino/Metabólico'),
('E02','Hipotireoidismo subclínico por deficiência de iodo','Endócrino/Metabólico'),
('E03','Outro hipotireoidismo','Endócrino/Metabólico'),('E04','Bócio não tóxico','Endócrino/Metabólico'),
('E05','Tireotoxicose (hipertireoidismo)','Endócrino/Metabólico'),('E06','Tireoidite','Endócrino/Metabólico'),
('E07','Outros transtornos da tireoide','Endócrino/Metabólico'),
('E10','Diabetes melito tipo 1','Endócrino/Metabólico'),('E11','Diabetes melito tipo 2','Endócrino/Metabólico'),
('E12','Diabetes melito relacionado com desnutrição','Endócrino/Metabólico'),
('E13','Outros tipos especificados de diabetes melito','Endócrino/Metabólico'),
('E14','Diabetes melito não especificado','Endócrino/Metabólico'),
('E15','Coma hipoglicêmico não diabético','Endócrino/Metabólico'),
('E16','Outros transtornos da secreção interna do pâncreas','Endócrino/Metabólico'),
('E20','Hipoparatireoidismo','Endócrino/Metabólico'),('E21','Hiperparatireoidismo','Endócrino/Metabólico'),
('E22','Hiperfunção da hipófise','Endócrino/Metabólico'),('E23','Hipofunção da hipófise','Endócrino/Metabólico'),
('E24','Síndrome de Cushing','Endócrino/Metabólico'),('E25','Transtornos adrenogenitais','Endócrino/Metabólico'),
('E26','Hiperaldosteronismo','Endócrino/Metabólico'),('E27','Outros transtornos da suprarrenal','Endócrino/Metabólico'),
('E28','Disfunção ovariana','Endócrino/Metabólico'),('E29','Disfunção testicular','Endócrino/Metabólico'),
('E30','Transtornos da puberdade','Endócrino/Metabólico'),
('E31','Disfunção poliglandular','Endócrino/Metabólico'),
('E34','Outros transtornos endócrinos','Endócrino/Metabólico'),
('E35','Transtornos das glândulas endócrinas em doenças classificadas em outra parte','Endócrino/Metabólico'),
('E40','Kwashiorkor','Endócrino/Metabólico'),('E41','Marasmo nutricional','Endócrino/Metabólico'),
('E42','Kwashiorkor marasmático','Endócrino/Metabólico'),('E43','Desnutrição proteico-calórica grave','Endócrino/Metabólico'),
('E44','Desnutrição proteico-calórica de grau moderado e leve','Endócrino/Metabólico'),
('E45','Retardo do desenvolvimento','Endócrino/Metabólico'),
('E46','Desnutrição proteico-calórica não especificada','Endócrino/Metabólico'),
('E50','Deficiência de vitamina A','Endócrino/Metabólico'),('E51','Deficiência de tiamina','Endócrino/Metabólico'),
('E52','Deficiência de niacina (pelagra)','Endócrino/Metabólico'),
('E53','Deficiências de outras vitaminas do grupo B','Endócrino/Metabólico'),
('E54','Deficiência de ácido ascórbico (escorbuto)','Endócrino/Metabólico'),
('E55','Deficiência de vitamina D (raquitismo)','Endócrino/Metabólico'),
('E56','Outras deficiências vitamínicas','Endócrino/Metabólico'),
('E58','Deficiência alimentar de cálcio','Endócrino/Metabólico'),
('E59','Deficiência alimentar de selênio','Endócrino/Metabólico'),
('E60','Deficiência alimentar de zinco','Endócrino/Metabólico'),
('E61','Deficiência de outros elementos nutrientes','Endócrino/Metabólico'),
('E63','Outras deficiências nutricionais','Endócrino/Metabólico'),
('E64','Sequelas de desnutrição','Endócrino/Metabólico'),
('E65','Adiposidade localizada','Endócrino/Metabólico'),('E66','Obesidade','Endócrino/Metabólico'),
('E67','Outras formas de hiperalimentação','Endócrino/Metabólico'),
('E68','Sequelas de hiperalimentação','Endócrino/Metabólico'),
('E70','Transtornos do metabolismo de aminoácidos aromáticos','Endócrino/Metabólico'),
('E71','Transtornos do metabolismo de aminoácidos de cadeia ramificada','Endócrino/Metabólico'),
('E72','Outros transtornos do metabolismo de aminoácidos','Endócrino/Metabólico'),
('E73','Intolerância à lactose','Endócrino/Metabólico'),('E74','Outros transtornos do metabolismo de carboidratos','Endócrino/Metabólico'),
('E75','Transtornos do metabolismo de esfingolipídios','Endócrino/Metabólico'),
('E76','Transtornos do metabolismo de glicosaminoglicanos','Endócrino/Metabólico'),
('E77','Transtornos do metabolismo de glicoproteínas','Endócrino/Metabólico'),
('E78','Transtornos do metabolismo das lipoproteínas','Endócrino/Metabólico'),
('E79','Transtornos do metabolismo das purinas e pirimidinas','Endócrino/Metabólico'),
('E80','Transtornos do metabolismo das porfirinas','Endócrino/Metabólico'),
('E83','Transtornos do metabolismo mineral','Endócrino/Metabólico'),
('E84','Fibrose cística','Endócrino/Metabólico'),('E85','Amiloidose','Endócrino/Metabólico'),
('E86','Depleção do volume','Endócrino/Metabólico'),('E87','Outros transtornos do equilíbrio hidroeletrolítico','Endócrino/Metabólico'),
('E88','Outros transtornos metabólicos','Endócrino/Metabólico'),
('E89','Transtornos endócrinos e metabólicos pós-procedimentos','Endócrino/Metabólico'),
('E90','Transtornos nutricionais e metabólicos em doenças classificadas em outra parte','Endócrino/Metabólico'),
-- ══ CAPÍTULO V — Transtornos mentais (F00–F99) ══
('F00','Demência na doença de Alzheimer','Mental/Comportamental'),
('F01','Demência vascular','Mental/Comportamental'),
('F02','Demência em outras doenças','Mental/Comportamental'),
('F03','Demência não especificada','Mental/Comportamental'),
('F04','Síndrome amnésica orgânica','Mental/Comportamental'),
('F05','Delirium não sobreposto à demência','Mental/Comportamental'),
('F06','Outros transtornos mentais devidos a lesão cerebral','Mental/Comportamental'),
('F07','Transtornos de personalidade e comportamento devidos a doença cerebral','Mental/Comportamental'),
('F09','Transtorno mental orgânico não especificado','Mental/Comportamental'),
('F10','Transtornos mentais e comportamentais devidos ao uso de álcool','Mental/Comportamental'),
('F11','Transtornos devidos ao uso de opioides','Mental/Comportamental'),
('F12','Transtornos devidos ao uso de canabinoides','Mental/Comportamental'),
('F13','Transtornos devidos ao uso de sedativos e hipnóticos','Mental/Comportamental'),
('F14','Transtornos devidos ao uso de cocaína','Mental/Comportamental'),
('F15','Transtornos devidos ao uso de outros estimulantes','Mental/Comportamental'),
('F16','Transtornos devidos ao uso de alucinógenos','Mental/Comportamental'),
('F17','Transtornos devidos ao uso de tabaco','Mental/Comportamental'),
('F18','Transtornos devidos ao uso de solventes voláteis','Mental/Comportamental'),
('F19','Transtornos devidos ao uso de múltiplas drogas','Mental/Comportamental'),
('F20','Esquizofrenia','Mental/Comportamental'),('F21','Transtorno esquizotípico','Mental/Comportamental'),
('F22','Transtornos delirantes persistentes','Mental/Comportamental'),
('F23','Transtornos psicóticos agudos','Mental/Comportamental'),
('F24','Transtorno delirante induzido','Mental/Comportamental'),
('F25','Transtornos esquizoafetivos','Mental/Comportamental'),
('F28','Outros transtornos psicóticos','Mental/Comportamental'),
('F29','Psicose não orgânica não especificada','Mental/Comportamental'),
('F30','Episódio maníaco','Mental/Comportamental'),('F31','Transtorno afetivo bipolar','Mental/Comportamental'),
('F32','Episódios depressivos','Mental/Comportamental'),('F33','Transtorno depressivo recorrente','Mental/Comportamental'),
('F34','Transtornos do humor persistentes','Mental/Comportamental'),
('F38','Outros transtornos do humor','Mental/Comportamental'),
('F39','Transtorno do humor não especificado','Mental/Comportamental'),
('F40','Transtornos fóbico-ansiosos','Mental/Comportamental'),
('F41','Outros transtornos ansiosos','Mental/Comportamental'),
('F42','Transtorno obsessivo-compulsivo','Mental/Comportamental'),
('F43','Reações ao estresse grave e transtornos de adaptação','Mental/Comportamental'),
('F44','Transtornos dissociativos (conversivos)','Mental/Comportamental'),
('F45','Transtornos somatoformes','Mental/Comportamental'),
('F48','Outros transtornos neuróticos','Mental/Comportamental'),
('F50','Transtornos alimentares','Mental/Comportamental'),
('F51','Transtornos não orgânicos do sono','Mental/Comportamental'),
('F52','Disfunção sexual de origem não orgânica','Mental/Comportamental'),
('F54','Fatores psicológicos associados a transtornos classificados em outra parte','Mental/Comportamental'),
('F60','Transtornos específicos de personalidade','Mental/Comportamental'),
('F61','Transtornos mistos de personalidade','Mental/Comportamental'),
('F63','Transtornos dos hábitos e dos impulsos','Mental/Comportamental'),
('F64','Transtornos de identidade sexual','Mental/Comportamental'),
('F65','Transtornos de preferência sexual','Mental/Comportamental'),
('F70','Retardo mental leve','Mental/Comportamental'),('F71','Retardo mental moderado','Mental/Comportamental'),
('F72','Retardo mental grave','Mental/Comportamental'),('F73','Retardo mental profundo','Mental/Comportamental'),
('F78','Outro retardo mental','Mental/Comportamental'),('F79','Retardo mental não especificado','Mental/Comportamental'),
('F80','Transtornos específicos do desenvolvimento da fala e da linguagem','Mental/Comportamental'),
('F81','Transtornos específicos do desenvolvimento das habilidades escolares','Mental/Comportamental'),
('F82','Transtorno específico do desenvolvimento motor','Mental/Comportamental'),
('F84','Transtornos globais do desenvolvimento','Mental/Comportamental'),
('F90','Transtornos hipercinéticos','Mental/Comportamental'),
('F91','Transtornos de conduta','Mental/Comportamental'),
('F92','Transtornos mistos de conduta e das emoções','Mental/Comportamental'),
('F93','Transtornos emocionais com início na infância','Mental/Comportamental'),
('F94','Transtornos do funcionamento social','Mental/Comportamental'),
('F95','Tiques','Mental/Comportamental'),('F98','Outros transtornos comportamentais na infância','Mental/Comportamental'),
('F99','Transtorno mental não especificado','Mental/Comportamental'),
-- ══ CAPÍTULO VI — Doenças do sistema nervoso (G00–G99) ══
('G00','Meningite bacteriana','Sistema Nervoso'),('G01','Meningite em doenças bacterianas','Sistema Nervoso'),
('G02','Meningite em outras doenças infecciosas','Sistema Nervoso'),
('G03','Meningite por outras causas e causas não especificadas','Sistema Nervoso'),
('G04','Encefalite, mielite e encefalomielite','Sistema Nervoso'),
('G05','Encefalite, mielite e encefalomielite em doenças classificadas em outra parte','Sistema Nervoso'),
('G06','Abscesso e granuloma intracranianos e intraspinais','Sistema Nervoso'),
('G07','Abscesso e granuloma intracranianos e intraspinais em doenças classificadas em outra parte','Sistema Nervoso'),
('G08','Flebite e tromboflebite intracranianas e intraspinais','Sistema Nervoso'),
('G09','Sequelas de doenças inflamatórias do SNC','Sistema Nervoso'),
('G10','Doença de Huntington','Sistema Nervoso'),('G11','Ataxias hereditárias','Sistema Nervoso'),
('G12','Atrofia muscular espinhal e síndromes correlatas','Sistema Nervoso'),
('G13','Atrofias sistêmicas que afetam principalmente o SNC','Sistema Nervoso'),
('G14','Síndrome pós-poliomielite','Sistema Nervoso'),
('G20','Doença de Parkinson','Sistema Nervoso'),('G21','Parkinsonismo secundário','Sistema Nervoso'),
('G22','Parkinsonismo em doenças classificadas em outra parte','Sistema Nervoso'),
('G23','Outras doenças degenerativas dos gânglios da base','Sistema Nervoso'),
('G24','Distonia','Sistema Nervoso'),('G25','Outros transtornos extrapiramidais e do movimento','Sistema Nervoso'),
('G26','Transtornos extrapiramidais e do movimento em doenças classificadas em outra parte','Sistema Nervoso'),
('G30','Doença de Alzheimer','Sistema Nervoso'),('G31','Outras doenças degenerativas do SNC','Sistema Nervoso'),
('G32','Outras doenças degenerativas do SNC em doenças classificadas em outra parte','Sistema Nervoso'),
('G35','Esclerose múltipla','Sistema Nervoso'),('G36','Outras desmielinizações agudas disseminadas','Sistema Nervoso'),
('G37','Outras doenças desmielinizantes do SNC','Sistema Nervoso'),
('G40','Epilepsia','Sistema Nervoso'),('G41','Estado de mal epiléptico','Sistema Nervoso'),
('G43','Enxaqueca','Sistema Nervoso'),('G44','Outras síndromes de algias cefálicas','Sistema Nervoso'),
('G45','Ataques isquêmicos transitórios cerebrais','Sistema Nervoso'),
('G46','Síndromes vasculares cerebrais em doenças cerebrovasculares','Sistema Nervoso'),
('G47','Transtornos do sono','Sistema Nervoso'),
('G50','Transtornos do nervo trigêmeo','Sistema Nervoso'),('G51','Transtornos do nervo facial','Sistema Nervoso'),
('G52','Transtornos de outros nervos cranianos','Sistema Nervoso'),
('G53','Transtornos dos nervos cranianos em doenças classificadas em outra parte','Sistema Nervoso'),
('G54','Transtornos das raízes e dos plexos nervosos','Sistema Nervoso'),
('G55','Compressões de raízes e plexos nervosos em doenças classificadas em outra parte','Sistema Nervoso'),
('G56','Mononeuropatias dos membros superiores','Sistema Nervoso'),
('G57','Mononeuropatias dos membros inferiores','Sistema Nervoso'),
('G58','Outras mononeuropatias','Sistema Nervoso'),
('G59','Mononeuropatia em doenças classificadas em outra parte','Sistema Nervoso'),
('G60','Neuropatia hereditária e idiopática','Sistema Nervoso'),
('G61','Polineuropatia inflamatória','Sistema Nervoso'),('G62','Outras polineuropatias','Sistema Nervoso'),
('G63','Polineuropatia em doenças classificadas em outra parte','Sistema Nervoso'),
('G64','Outros transtornos do sistema nervoso periférico','Sistema Nervoso'),
('G70','Miastenia grave e outros transtornos neuromusculares','Sistema Nervoso'),
('G71','Transtornos primários dos músculos','Sistema Nervoso'),
('G72','Outras miopatias','Sistema Nervoso'),('G73','Transtornos da junção neuromuscular e músculo em doenças classificadas em outra parte','Sistema Nervoso'),
('G80','Paralisia cerebral','Sistema Nervoso'),('G81','Hemiplegia','Sistema Nervoso'),
('G82','Paraplegia e tetraplegia','Sistema Nervoso'),('G83','Outras síndromes paralíticas','Sistema Nervoso'),
('G89','Dor não classificada em outra parte','Sistema Nervoso'),
('G90','Transtornos do sistema nervoso autônomo','Sistema Nervoso'),
('G91','Hidrocefalia','Sistema Nervoso'),('G92','Encefalopatia tóxica','Sistema Nervoso'),
('G93','Outros transtornos encefálicos','Sistema Nervoso'),('G94','Outros transtornos encefálicos em doenças classificadas em outra parte','Sistema Nervoso'),
('G95','Outras doenças da medula espinhal','Sistema Nervoso'),
('G96','Outros transtornos do sistema nervoso central','Sistema Nervoso'),
('G97','Transtornos pós-procedimentos do sistema nervoso','Sistema Nervoso'),
('G98','Outros transtornos do sistema nervoso','Sistema Nervoso'),
('G99','Outros transtornos do sistema nervoso em doenças classificadas em outra parte','Sistema Nervoso'),
-- ══ CAPÍTULO VII — Olho e anexos (H00–H59) ══
('H00','Hordéolo e calázio','Olho'),('H01','Outras inflamações da pálpebra','Olho'),
('H02','Outros transtornos da pálpebra','Olho'),('H04','Transtornos do aparelho lacrimal','Olho'),
('H05','Transtornos da órbita','Olho'),('H10','Conjuntivite','Olho'),
('H11','Outros transtornos da conjuntiva','Olho'),('H15','Transtornos da esclera','Olho'),
('H16','Ceratite','Olho'),('H17','Cicatrizes e opacidades da córnea','Olho'),
('H18','Outros transtornos da córnea','Olho'),('H20','Iridociclite','Olho'),
('H25','Catarata senil','Olho'),('H26','Outras formas de catarata','Olho'),
('H27','Outros transtornos do cristalino','Olho'),('H30','Inflamação coriorretiniana','Olho'),
('H33','Descolamento e defeitos da retina','Olho'),('H34','Oclusões vasculares da retina','Olho'),
('H35','Outros transtornos da retina','Olho'),('H40','Glaucoma','Olho'),
('H43','Transtornos do humor vítreo','Olho'),('H44','Transtornos do globo ocular','Olho'),
('H46','Neurite óptica','Olho'),('H47','Outros transtornos do nervo óptico','Olho'),
('H49','Estrabismo paralítico','Olho'),('H50','Outros estrabismos','Olho'),
('H52','Transtornos da refração e da acomodação','Olho'),
('H53','Perturbações visuais','Olho'),('H54','Cegueira e visão subnormal','Olho'),
('H55','Nistagmo e outros movimentos oculares irregulares','Olho'),
('H57','Outros transtornos do olho e anexos','Olho'),
-- ══ CAPÍTULO VIII — Ouvido (H60–H95) ══
('H60','Otite externa','Ouvido'),('H61','Outros transtornos do ouvido externo','Ouvido'),
('H65','Otite média não supurativa','Ouvido'),('H66','Otite média supurativa','Ouvido'),
('H67','Otite média em doenças classificadas em outra parte','Ouvido'),
('H68','Inflamação da tuba de Eustáquio','Ouvido'),('H70','Mastoidite','Ouvido'),
('H72','Perfuração da membrana timpânica','Ouvido'),('H74','Outros transtornos do ouvido médio','Ouvido'),
('H80','Otosclerose','Ouvido'),('H81','Transtornos da função vestibular','Ouvido'),
('H83','Outros transtornos do ouvido interno','Ouvido'),('H90','Perda de audição','Ouvido'),
('H91','Outras perdas de audição','Ouvido'),('H92','Otalgia e otorreia','Ouvido'),
('H93','Outros transtornos do ouvido','Ouvido'),('H95','Transtornos pós-procedimentos do ouvido e apófise mastóide','Ouvido'),
-- ══ CAPÍTULO IX — Doenças do aparelho circulatório (I00–I99) ══
('I00','Febre reumática sem menção de comprometimento do coração','Cardiovascular'),
('I01','Febre reumática com comprometimento do coração','Cardiovascular'),
('I02','Coréia reumática','Cardiovascular'),
('I05','Doenças reumáticas da valva mitral','Cardiovascular'),('I06','Doenças reumáticas da valva aórtica','Cardiovascular'),
('I07','Doenças reumáticas da valva tricúspide','Cardiovascular'),
('I08','Doenças de múltiplas valvas','Cardiovascular'),('I09','Outras doenças reumáticas do coração','Cardiovascular'),
('I10','Hipertensão essencial (primária)','Cardiovascular'),
('I11','Doença cardíaca hipertensiva','Cardiovascular'),('I12','Doença renal hipertensiva','Cardiovascular'),
('I13','Doença cardíaca e renal hipertensiva','Cardiovascular'),('I15','Hipertensão secundária','Cardiovascular'),
('I20','Angina pectoris','Cardiovascular'),('I21','Infarto agudo do miocárdio','Cardiovascular'),
('I21.0','IAM da parede anterior','Cardiovascular'),('I21.1','IAM da parede inferior','Cardiovascular'),
('I21.2','IAM de outras paredes','Cardiovascular'),('I21.3','IAM transmural de localização não especificada','Cardiovascular'),
('I21.4','IAM subendocárdico','Cardiovascular'),('I21.9','IAM não especificado','Cardiovascular'),
('I22','Infarto do miocárdio recorrente','Cardiovascular'),
('I23','Complicações do infarto agudo do miocárdio','Cardiovascular'),
('I24','Outras doenças isquêmicas agudas do coração','Cardiovascular'),
('I25','Doença isquêmica crônica do coração','Cardiovascular'),
('I26','Embolia pulmonar','Cardiovascular'),('I27','Outras doenças pulmonares do coração','Cardiovascular'),
('I28','Outras doenças dos vasos pulmonares','Cardiovascular'),
('I30','Pericardite aguda','Cardiovascular'),('I31','Outras doenças do pericárdio','Cardiovascular'),
('I32','Pericardite em doenças classificadas em outra parte','Cardiovascular'),
('I33','Endocardite aguda e subaguda','Cardiovascular'),('I34','Transtornos não reumáticos da valva mitral','Cardiovascular'),
('I35','Transtornos não reumáticos da valva aórtica','Cardiovascular'),
('I36','Transtornos não reumáticos da valva tricúspide','Cardiovascular'),
('I37','Transtornos da valva pulmonar','Cardiovascular'),
('I38','Endocardite de valva não especificada','Cardiovascular'),
('I40','Miocardite aguda','Cardiovascular'),('I41','Miocardite em doenças classificadas em outra parte','Cardiovascular'),
('I42','Cardiomiopatias','Cardiovascular'),('I43','Cardiomiopatia em doenças classificadas em outra parte','Cardiovascular'),
('I44','Bloqueio atrioventricular e do ramo esquerdo','Cardiovascular'),
('I45','Outros transtornos da condução','Cardiovascular'),('I46','Parada cardíaca','Cardiovascular'),
('I47','Taquicardia paroxística','Cardiovascular'),('I48','Fibrilação e flutter atriais','Cardiovascular'),
('I49','Outras arritmias cardíacas','Cardiovascular'),('I50','Insuficiência cardíaca','Cardiovascular'),
('I51','Complicações e doenças cardíacas mal definidas','Cardiovascular'),
('I52','Outros transtornos cardíacos em doenças classificadas em outra parte','Cardiovascular'),
('I60','Hemorragia subaracnóidea','Cardiovascular'),('I61','Hemorragia intracerebral','Cardiovascular'),
('I62','Outras hemorragias intracranianas não traumáticas','Cardiovascular'),
('I63','Infarto cerebral','Cardiovascular'),('I64','Acidente vascular cerebral não especificado como hemorrágico ou isquêmico','Cardiovascular'),
('I65','Oclusão e estenose das artérias pré-cerebrais','Cardiovascular'),
('I66','Oclusão e estenose das artérias cerebrais','Cardiovascular'),
('I67','Outras doenças cerebrovasculares','Cardiovascular'),
('I68','Transtornos cerebrovasculares em doenças classificadas em outra parte','Cardiovascular'),
('I69','Sequelas de doenças cerebrovasculares','Cardiovascular'),
('I70','Aterosclerose','Cardiovascular'),('I71','Aneurisma e dissecção aórtica','Cardiovascular'),
('I72','Outro aneurisma','Cardiovascular'),('I73','Outras doenças vasculares periféricas','Cardiovascular'),
('I74','Embolia e trombose arteriais','Cardiovascular'),
('I77','Outras doenças das artérias e arteríolas','Cardiovascular'),
('I78','Doenças dos capilares','Cardiovascular'),
('I80','Flebite e tromboflebite','Cardiovascular'),
('I81','Trombose da veia porta','Cardiovascular'),
('I82','Outras embolias e tromboses venosas','Cardiovascular'),
('I83','Varizes dos membros inferiores','Cardiovascular'),
('I84','Hemorroidas','Cardiovascular'),('I85','Varizes esofagianas','Cardiovascular'),
('I86','Varizes de outras localizações','Cardiovascular'),
('I87','Outros transtornos das veias','Cardiovascular'),
('I88','Linfadenite inespecífica','Cardiovascular'),('I89','Outros transtornos não infecciosos dos vasos linfáticos','Cardiovascular'),
('I95','Hipotensão','Cardiovascular'),('I97','Transtornos do aparelho circulatório pós-procedimentos','Cardiovascular'),
('I98','Outros transtornos do aparelho circulatório em doenças classificadas em outra parte','Cardiovascular'),
('I99','Outros transtornos do aparelho circulatório e os não especificados','Cardiovascular'),
-- ══ CAPÍTULO X — Doenças do aparelho respiratório (J00–J99) ══
('J00','Nasofaringite aguda (resfriado comum)','Respiratório'),
('J01','Sinusite aguda','Respiratório'),('J02','Faringite aguda','Respiratório'),
('J03','Amigdalite aguda','Respiratório'),('J04','Laringite e traqueíte agudas','Respiratório'),
('J05','Laringotraqueíte obstrutiva aguda e epiglotite','Respiratório'),
('J06','Infecções agudas das vias aéreas superiores de localizações múltiplas','Respiratório'),
('J09','Influenza devida a vírus identificado','Respiratório'),
('J10','Influenza devida a outro vírus da influenza identificado','Respiratório'),
('J11','Influenza devida a vírus não identificado','Respiratório'),
('J12','Pneumonia viral','Respiratório'),('J13','Pneumonia a Streptococcus pneumoniae','Respiratório'),
('J14','Pneumonia a Haemophilus influenzae','Respiratório'),('J15','Pneumonia bacteriana','Respiratório'),
('J15.0','Pneumonia a Klebsiella pneumoniae','Respiratório'),
('J15.1','Pneumonia a Pseudomonas','Respiratório'),
('J15.2','Pneumonia a estafilococos','Respiratório'),
('J15.3','Pneumonia a estreptococos do grupo B','Respiratório'),
('J15.4','Pneumonia a outros estreptococos','Respiratório'),
('J15.5','Pneumonia a Escherichia coli','Respiratório'),
('J15.6','Pneumonia a outras bactérias aeróbias Gram-negativas','Respiratório'),
('J15.7','Pneumonia a Mycoplasma pneumoniae','Respiratório'),
('J15.8','Outras pneumonias bacterianas','Respiratório'),
('J15.9','Pneumonia bacteriana não especificada','Respiratório'),
('J16','Pneumonia por outros microorganismos','Respiratório'),
('J17','Pneumonia em doenças classificadas em outra parte','Respiratório'),
('J18','Pneumonia não especificada','Respiratório'),
('J18.0','Pneumonia lobar não especificada','Respiratório'),
('J18.1','Pneumonia lobar não especificada','Respiratório'),
('J18.2','Pneumonia hipostática não especificada','Respiratório'),
('J18.9','Pneumonia não especificada','Respiratório'),
('J20','Bronquite aguda','Respiratório'),('J21','Bronquiolite aguda','Respiratório'),
('J22','Infecção aguda não especificada das vias aéreas inferiores','Respiratório'),
('J30','Rinite alérgica e vasomotora','Respiratório'),('J31','Rinite, nasofaringite e faringite crônicas','Respiratório'),
('J32','Sinusite crônica','Respiratório'),('J33','Pólipo nasal','Respiratório'),
('J34','Outros transtornos do nariz e dos seios paranasais','Respiratório'),
('J35','Doenças crônicas das amígdalas e das adenoides','Respiratório'),
('J36','Abscesso periamigdaliano','Respiratório'),('J37','Laringite e laringotraqueíte crônicas','Respiratório'),
('J38','Doenças das cordas vocais e da laringe','Respiratório'),
('J39','Outras doenças das vias respiratórias superiores','Respiratório'),
('J40','Bronquite não especificada como aguda ou crônica','Respiratório'),
('J41','Bronquite crônica simples e mucopurulenta','Respiratório'),
('J42','Bronquite crônica não especificada','Respiratório'),
('J43','Enfisema','Respiratório'),('J44','Outras doenças pulmonares obstrutivas crônicas','Respiratório'),
('J45','Asma','Respiratório'),('J46','Estado de mal asmático','Respiratório'),
('J47','Bronquiectasia','Respiratório'),
('J60','Pneumoconiose dos mineiros do carvão','Respiratório'),
('J61','Pneumoconiose devida a amianto','Respiratório'),('J62','Pneumoconiose devida a poeira de sílica','Respiratório'),
('J63','Pneumoconiose devida a outras poeiras inorgânicas','Respiratório'),
('J64','Pneumoconiose não especificada','Respiratório'),
('J65','Pneumoconiose associada à tuberculose','Respiratório'),
('J66','Doenças das vias aéreas devidas a poeiras orgânicas específicas','Respiratório'),
('J67','Pneumonite por hipersensibilidade devida a poeira orgânica','Respiratório'),
('J68','Afecções respiratórias devidas à inalação de produtos químicos','Respiratório'),
('J69','Pneumonite devida a sólidos e líquidos','Respiratório'),
('J70','Afecções respiratórias devidas a outros agentes externos','Respiratório'),
('J80','Síndrome do desconforto respiratório do adulto','Respiratório'),
('J81','Edema pulmonar','Respiratório'),('J82','Eosinofilia pulmonar','Respiratório'),
('J84','Outras doenças pulmonares intersticiais','Respiratório'),
('J85','Abscesso do pulmão e do mediastino','Respiratório'),
('J86','Piotórax','Respiratório'),('J90','Derrame pleural','Respiratório'),
('J91','Derrame pleural em afecções classificadas em outra parte','Respiratório'),
('J92','Placas pleurais','Respiratório'),('J93','Pneumotórax','Respiratório'),
('J94','Outras afecções pleurais','Respiratório'),
('J95','Afecções respiratórias pós-procedimentos','Respiratório'),
('J96','Insuficiência respiratória não classificada em outra parte','Respiratório'),
('J98','Outros transtornos respiratórios','Respiratório'),
('J99','Transtornos respiratórios em doenças classificadas em outra parte','Respiratório'),
-- ══ CAPÍTULO XI — Doenças do aparelho digestivo (K00–K93) ══
('K00','Transtornos do desenvolvimento e da erupção dos dentes','Digestivo'),
('K01','Dentes inclusos e impactados','Digestivo'),('K02','Cárie dentária','Digestivo'),
('K05','Gengivite e doenças periodontais','Digestivo'),('K08','Outros transtornos dos dentes','Digestivo'),
('K11','Doenças das glândulas salivares','Digestivo'),('K12','Estomatite e lesões correlatas','Digestivo'),
('K13','Outras doenças do lábio e da mucosa oral','Digestivo'),
('K14','Doenças da língua','Digestivo'),
('K20','Esofagite','Digestivo'),('K21','Doença do refluxo gastroesofágico','Digestivo'),
('K22','Outras doenças do esôfago','Digestivo'),('K25','Úlcera gástrica','Digestivo'),
('K26','Úlcera duodenal','Digestivo'),('K27','Úlcera péptica de localização não especificada','Digestivo'),
('K28','Úlcera gastrojejunal','Digestivo'),
('K29','Gastrite e duodenite','Digestivo'),('K30','Dispepsia','Digestivo'),
('K31','Outras doenças do estômago e do duodeno','Digestivo'),
('K35','Apendicite aguda com peritonite generalizada','Digestivo'),
('K36','Outras formas de apendicite','Digestivo'),('K37','Apendicite não especificada','Digestivo'),
('K38','Outras doenças do apêndice','Digestivo'),
('K40','Hérnia inguinal','Digestivo'),('K41','Hérnia femoral','Digestivo'),
('K42','Hérnia umbilical','Digestivo'),('K43','Hérnia ventral','Digestivo'),
('K44','Hérnia diafragmática','Digestivo'),('K45','Outras hérnias abdominais','Digestivo'),
('K46','Hérnia abdominal não especificada','Digestivo'),
('K50','Doença de Crohn','Digestivo'),('K51','Colite ulcerativa','Digestivo'),
('K52','Outras gastroenterites e colites','Digestivo'),
('K55','Transtornos vasculares do intestino','Digestivo'),
('K56','Íleo paralítico e obstrução intestinal','Digestivo'),
('K57','Doença diverticular do intestino','Digestivo'),('K58','Síndrome do intestino irritável','Digestivo'),
('K59','Outros transtornos funcionais do intestino','Digestivo'),
('K60','Fissura e fístula das regiões anal e retal','Digestivo'),
('K61','Abscesso da região anal e retal','Digestivo'),('K62','Outras doenças do ânus e do reto','Digestivo'),
('K63','Outras doenças do intestino','Digestivo'),('K65','Peritonite','Digestivo'),
('K66','Outros transtornos do peritônio','Digestivo'),
('K70','Doença alcoólica do fígado','Digestivo'),('K71','Doença hepática tóxica','Digestivo'),
('K72','Insuficiência hepática','Digestivo'),('K73','Hepatite crônica','Digestivo'),
('K74','Fibrose e cirrose hepática','Digestivo'),('K75','Outras doenças inflamatórias do fígado','Digestivo'),
('K76','Outras doenças do fígado','Digestivo'),('K77','Transtornos do fígado em doenças classificadas em outra parte','Digestivo'),
('K80','Colelitíase (cálculo biliar)','Digestivo'),('K81','Colecistite','Digestivo'),
('K82','Outras doenças da vesícula biliar','Digestivo'),('K83','Outras doenças das vias biliares','Digestivo'),
('K85','Pancreatite aguda','Digestivo'),('K86','Outras doenças do pâncreas','Digestivo'),
('K87','Transtornos da vesícula biliar, vias biliares e pâncreas em doenças classificadas em outra parte','Digestivo'),
('K90','Má-absorção intestinal','Digestivo'),('K91','Transtornos do aparelho digestivo pós-procedimentos','Digestivo'),
('K92','Outras doenças do aparelho digestivo','Digestivo'),
('K93','Transtornos dos órgãos digestivos em doenças classificadas em outra parte','Digestivo'),
-- ══ CAPÍTULO XII — Doenças da pele (L00–L99) ══
('L00','Síndrome estafilocócica da pele escaldada (SSSS)','Pele'),
('L01','Impetigo','Pele'),('L02','Abscesso cutâneo, furúnculo e antraz','Pele'),
('L03','Celulite','Pele'),('L04','Linfadenite aguda','Pele'),
('L05','Cisto pilonidal','Pele'),('L08','Outras infecções locais da pele e tecido subcutâneo','Pele'),
('L10','Pênfigo','Pele'),('L12','Penfigoide','Pele'),('L13','Outros transtornos bolhosos','Pele'),
('L20','Dermatite atópica','Pele'),('L21','Dermatite seborreica','Pele'),
('L22','Dermatite das fraldas','Pele'),('L23','Dermatite alérgica de contato','Pele'),
('L24','Dermatite de contato por irritante','Pele'),('L25','Dermatite de contato não especificada','Pele'),
('L26','Dermatite esfoliativa','Pele'),('L27','Dermatite devida a substâncias ingeridas','Pele'),
('L28','Líquen simples crônico e prurigo','Pele'),('L29','Prurido','Pele'),
('L30','Outras dermatites','Pele'),('L40','Psoríase','Pele'),('L41','Parapsoriase','Pele'),
('L42','Pitiríase rósea','Pele'),('L43','Líquen plano','Pele'),('L44','Outras doenças papuloescamosas','Pele'),
('L50','Urticária','Pele'),('L51','Eritema multiforme','Pele'),('L52','Eritema nodoso','Pele'),
('L53','Outras afecções eritematosas','Pele'),('L55','Queimadura solar','Pele'),
('L56','Outras alterações agudas da pele devidas a radiação ultravioleta','Pele'),
('L57','Alterações da pele devidas à exposição crônica à radiação não-ionizante','Pele'),
('L60','Transtornos das unhas','Pele'),('L63','Alopecia areata','Pele'),
('L64','Alopecia androgênica','Pele'),('L66','Transtornos cicatriciais com perda de cabelo','Pele'),
('L70','Acne','Pele'),('L71','Rosácea','Pele'),('L72','Cistos foliculares da pele e tecido subcutâneo','Pele'),
('L73','Outros transtornos foliculares','Pele'),('L80','Vitiligo','Pele'),
('L81','Outros transtornos da pigmentação','Pele'),('L82','Ceratose seborréica','Pele'),
('L83','Acantose nigricante','Pele'),('L84','Calosidade','Pele'),
('L85','Outras formas de espessamento epidérmico','Pele'),
('L89','Úlcera de decúbito (úlcera por pressão)','Pele'),
('L90','Afecções atróficas da pele','Pele'),('L91','Afecções hipertróficas da pele','Pele'),
('L92','Afecções granulomatosas da pele e do tecido subcutâneo','Pele'),
('L93','Lúpus eritematoso','Pele'),('L94','Outras afecções localizadas do tecido conjuntivo','Pele'),
('L95','Vasculite limitada à pele','Pele'),('L97','Úlcera do membro inferior','Pele'),
('L98','Outras afecções da pele e do tecido subcutâneo','Pele'),
-- ══ CAPÍTULO XIII — Sistema musculoesquelético (M00–M99) ══
('M00','Artrite piogênica','Musculoesquelético'),('M01','Artrite infecciosa em doenças classificadas em outra parte','Musculoesquelético'),
('M02','Artropatias reativas','Musculoesquelético'),('M05','Artrite reumatoide soropositiva','Musculoesquelético'),
('M06','Outras artrites reumatoides','Musculoesquelético'),('M07','Artropatias psoriásicas e enteropáticas','Musculoesquelético'),
('M08','Artrite juvenil','Musculoesquelético'),('M10','Gota','Musculoesquelético'),
('M11','Outros transtornos por depósito de cristais','Musculoesquelético'),
('M12','Outras artropatias específicas','Musculoesquelético'),('M13','Outras artrites','Musculoesquelético'),
('M15','Poliartrose','Musculoesquelético'),('M16','Coxartrose','Musculoesquelético'),
('M17','Gonartrose','Musculoesquelético'),('M18','Artrose da primeira articulação carpometacarpal','Musculoesquelético'),
('M19','Outras artroses','Musculoesquelético'),
('M20','Deformidades adquiridas dos dedos das mãos e dos pés','Musculoesquelético'),
('M21','Outras deformidades adquiridas dos membros','Musculoesquelético'),
('M23','Transtornos internos dos joelhos','Musculoesquelético'),
('M24','Outros transtornos articulares específicos','Musculoesquelético'),
('M25','Outros transtornos articulares','Musculoesquelético'),
('M30','Poliarterite nodosa e afecções correlatas','Musculoesquelético'),
('M31','Outras vasculopatias necrosantes','Musculoesquelético'),
('M32','Lúpus eritematoso sistêmico','Musculoesquelético'),('M33','Dermatopoliomiosite','Musculoesquelético'),
('M34','Esclerose sistêmica','Musculoesquelético'),('M35','Outras afecções sistêmicas do tecido conjuntivo','Musculoesquelético'),
('M36','Afecções sistêmicas do tecido conjuntivo em doenças classificadas em outra parte','Musculoesquelético'),
('M40','Cifose e lordose','Musculoesquelético'),('M41','Escoliose','Musculoesquelético'),
('M43','Outras dorsopatias deformantes','Musculoesquelético'),
('M45','Espondilite anquilosante','Musculoesquelético'),('M46','Outras espondilopatias inflamatórias','Musculoesquelético'),
('M47','Espondilose','Musculoesquelético'),('M48','Outras espondilopatias','Musculoesquelético'),
('M50','Transtornos dos discos cervicais','Musculoesquelético'),('M51','Outros transtornos de discos intervertebrais','Musculoesquelético'),
('M54','Dorsalgia','Musculoesquelético'),('M60','Miosite','Musculoesquelético'),
('M61','Calcificação e ossificação do músculo','Musculoesquelético'),
('M62','Outros transtornos dos músculos','Musculoesquelético'),
('M65','Sinovite e tenossinovite','Musculoesquelético'),('M66','Ruptura espontânea de sinóvia e de tendão','Musculoesquelético'),
('M67','Outros transtornos da sinóvia e do tendão','Musculoesquelético'),
('M70','Afecções dos tecidos moles relacionadas com o uso, o uso excessivo e a pressão','Musculoesquelético'),
('M71','Outras bursopatias','Musculoesquelético'),('M75','Lesões do ombro','Musculoesquelético'),
('M76','Entesopatias do membro inferior','Musculoesquelético'),
('M77','Outras entesopatias','Musculoesquelético'),('M79','Outros transtornos dos tecidos moles','Musculoesquelético'),
('M80','Osteoporose com fratura patológica','Musculoesquelético'),
('M81','Osteoporose sem fratura patológica','Musculoesquelético'),
('M83','Osteomalácia do adulto','Musculoesquelético'),('M84','Transtornos da continuidade do osso','Musculoesquelético'),
('M85','Outros transtornos da densidade e da estrutura do osso','Musculoesquelético'),
('M86','Osteomielite','Musculoesquelético'),('M87','Osteonecrose','Musculoesquelético'),
('M88','Doença de Paget (osteíte deformante)','Musculoesquelético'),
('M89','Outros transtornos dos ossos','Musculoesquelético'),
('M90','Osteopatias em doenças classificadas em outra parte','Musculoesquelético'),
('M91','Osteocondrose juvenil do quadril e da pelve','Musculoesquelético'),
('M92','Outras osteocondroses juvenis','Musculoesquelético'),
('M93','Outras osteocondroses','Musculoesquelético'),('M94','Outros transtornos das cartilagens','Musculoesquelético'),
('M95','Outras deformidades adquiridas do sistema musculoesquelético','Musculoesquelético'),
('M96','Afecções musculoesqueléticas pós-procedimentos','Musculoesquelético'),
('M99','Lesões biomecânicas','Musculoesquelético'),
-- ══ CAPÍTULO XIV — Aparelho geniturinário (N00–N99) ══
('N00','Síndrome nefrítica aguda','Geniturinário'),('N01','Síndrome nefrítica rapidamente progressiva','Geniturinário'),
('N02','Hematúria recidivante e persistente','Geniturinário'),('N03','Síndrome nefrítica crônica','Geniturinário'),
('N04','Síndrome nefrótica','Geniturinário'),('N05','Síndrome nefrítica não especificada','Geniturinário'),
('N06','Proteinúria isolada com lesão morfológica especificada','Geniturinário'),
('N07','Nefropatia hereditária','Geniturinário'),('N08','Afecções glomerulares em doenças classificadas em outra parte','Geniturinário'),
('N10','Nefrite tubulointersticial aguda','Geniturinário'),
('N11','Nefrite tubulointersticial crônica','Geniturinário'),
('N12','Nefrite tubulointersticial não especificada','Geniturinário'),
('N13','Uropatia obstrutiva e por refluxo','Geniturinário'),
('N14','Afecções tubulares e tubulointersticiais induzidas por drogas e metais pesados','Geniturinário'),
('N15','Outras nefropatias tubulointersticiais','Geniturinário'),
('N17','Insuficiência renal aguda','Geniturinário'),
('N17.0','Insuficiência renal aguda com necrose tubular','Geniturinário'),
('N17.1','Insuficiência renal aguda com necrose cortical aguda','Geniturinário'),
('N17.9','Insuficiência renal aguda não especificada','Geniturinário'),
('N18','Insuficiência renal crônica','Geniturinário'),
('N18.1','Doença renal crônica estágio 1','Geniturinário'),
('N18.2','Doença renal crônica estágio 2','Geniturinário'),
('N18.3','Doença renal crônica estágio 3','Geniturinário'),
('N18.4','Doença renal crônica estágio 4','Geniturinário'),
('N18.5','Doença renal crônica estágio 5','Geniturinário'),
('N18.9','Doença renal crônica não especificada','Geniturinário'),
('N19','Insuficiência renal não especificada','Geniturinário'),
('N20','Calculose do rim e do ureter','Geniturinário'),('N21','Calculose do trato urinário inferior','Geniturinário'),
('N23','Cólica renal não especificada','Geniturinário'),
('N25','Transtornos resultantes de função tubular renal alterada','Geniturinário'),
('N26','Rim contraído não especificado','Geniturinário'),('N27','Rim pequeno de causa desconhecida','Geniturinário'),
('N28','Outros transtornos do rim e do ureter','Geniturinário'),
('N30','Cistite','Geniturinário'),('N31','Disfunções neuromusculares da bexiga','Geniturinário'),
('N32','Outros transtornos da bexiga','Geniturinário'),('N34','Uretrite e síndrome uretral','Geniturinário'),
('N35','Estenose da uretra','Geniturinário'),('N39','Outros transtornos do trato urinário','Geniturinário'),
('N39.0','Infecção do trato urinário de localização não especificada','Geniturinário'),
('N40','Hiperplasia da próstata','Geniturinário'),('N41','Doenças inflamatórias da próstata','Geniturinário'),
('N42','Outros transtornos da próstata','Geniturinário'),
('N43','Hidrocele e espermatocele','Geniturinário'),('N44','Torção do testículo','Geniturinário'),
('N45','Orquite e epididimite','Geniturinário'),
('N46','Infertilidade masculina','Geniturinário'),('N47','Prepúcio redundante, fimose e parafimose','Geniturinário'),
('N48','Outros transtornos do pênis','Geniturinário'),
('N60','Displasia mamária benigna','Geniturinário'),('N61','Doenças inflamatórias da mama','Geniturinário'),
('N62','Hipertrofia da mama','Geniturinário'),('N63','Nódulo não especificado na mama','Geniturinário'),
('N70','Salpingite e ooforite','Geniturinário'),('N71','Doença inflamatória do útero','Geniturinário'),
('N72','Doença inflamatória do colo do útero','Geniturinário'),
('N73','Outras doenças inflamatórias pélvicas femininas','Geniturinário'),
('N74','Transtornos inflamatórios dos órgãos pélvicos femininos em doenças classificadas em outra parte','Geniturinário'),
('N75','Doenças da glândula de Bartholin','Geniturinário'),
('N76','Outras afecções inflamatórias da vagina e da vulva','Geniturinário'),
('N80','Endometriose','Geniturinário'),('N81','Prolapso genital feminino','Geniturinário'),
('N83','Transtornos não inflamatórios do ovário, da tuba de Falópio e do ligamento largo','Geniturinário'),
('N84','Pólipo do trato genital feminino','Geniturinário'),
('N85','Outros transtornos não inflamatórios do útero','Geniturinário'),
('N87','Displasia do colo do útero','Geniturinário'),
('N89','Outros transtornos não inflamatórios da vagina','Geniturinário'),
('N90','Outros transtornos não inflamatórios da vulva e do períneo','Geniturinário'),
('N91','Menstruação ausente, escassa ou rara','Geniturinário'),
('N92','Menstruação excessiva, frequente e irregular','Geniturinário'),
('N93','Outras hemorragias uterinas ou vaginais anormais','Geniturinário'),
('N94','Dor e outras afecções associadas aos órgãos genitais femininos','Geniturinário'),
('N95','Transtornos da menopausa e da perimenopausa','Geniturinário'),
('N96','Abortamento habitual','Geniturinário'),
('N97','Infertilidade feminina','Geniturinário'),
('N99','Transtornos do aparelho geniturinário pós-procedimentos','Geniturinário'),
-- ══ CAPÍTULO XV — Gravidez, parto e puerpério (O00–O99) ══
('O00','Gravidez ectópica','Gravidez/Parto'),('O01','Mola hidatiforme','Gravidez/Parto'),
('O02','Outros produtos anormais da concepção','Gravidez/Parto'),
('O03','Aborto espontâneo','Gravidez/Parto'),('O04','Aborto por razões médicas','Gravidez/Parto'),
('O05','Outros tipos de aborto','Gravidez/Parto'),('O06','Aborto não especificado','Gravidez/Parto'),
('O07','Falha de tentativa de aborto','Gravidez/Parto'),
('O08','Complicações conseqüentes a aborto e gravidez ectópica e molar','Gravidez/Parto'),
('O10','Hipertensão pré-existente complicando a gravidez','Gravidez/Parto'),
('O11','Transtorno hipertensivo pré-existente com proteinúria superposta','Gravidez/Parto'),
('O12','Edema e proteinúria gestacionais sem hipertensão','Gravidez/Parto'),
('O13','Hipertensão gestacional sem proteinúria significativa','Gravidez/Parto'),
('O14','Pré-eclâmpsia','Gravidez/Parto'),('O15','Eclâmpsia','Gravidez/Parto'),
('O16','Hipertensão materna não especificada','Gravidez/Parto'),
('O20','Hemorragia do início da gravidez','Gravidez/Parto'),
('O21','Vômitos excessivos na gravidez','Gravidez/Parto'),
('O22','Complicações venosas na gravidez','Gravidez/Parto'),
('O23','Infecções do trato geniturinário na gravidez','Gravidez/Parto'),
('O24','Diabetes melito na gravidez','Gravidez/Parto'),
('O25','Desnutrição na gravidez','Gravidez/Parto'),
('O26','Cuidados maternos por outras afecções predominantemente relacionadas com a gravidez','Gravidez/Parto'),
('O30','Gestação múltipla','Gravidez/Parto'),('O31','Complicações específicas de gestação múltipla','Gravidez/Parto'),
('O34','Cuidados maternos por anormalidades conhecidas ou suspeitas dos órgãos pélvicos da mãe','Gravidez/Parto'),
('O36','Cuidados maternos por outros problemas fetais conhecidos ou suspeitos','Gravidez/Parto'),
('O40','Polihidrâmnio','Gravidez/Parto'),('O41','Outros transtornos do líquido amniótico','Gravidez/Parto'),
('O42','Ruptura prematura de membranas','Gravidez/Parto'),
('O43','Transtornos placentários','Gravidez/Parto'),('O44','Placenta prévia','Gravidez/Parto'),
('O45','Descolamento prematuro da placenta','Gravidez/Parto'),
('O46','Hemorragia anteparto','Gravidez/Parto'),('O47','Falso trabalho de parto','Gravidez/Parto'),
('O60','Trabalho de parto pré-termo','Gravidez/Parto'),
('O62','Anormalidades da contração uterina','Gravidez/Parto'),
('O63','Trabalho de parto prolongado','Gravidez/Parto'),
('O64','Trabalho de parto obstruído por má-apresentação do feto','Gravidez/Parto'),
('O65','Trabalho de parto obstruído por anormalidade pélvica','Gravidez/Parto'),
('O66','Outras causas de trabalho de parto obstruído','Gravidez/Parto'),
('O67','Trabalho de parto e parto complicados por hemorragia','Gravidez/Parto'),
('O68','Trabalho de parto e parto complicados por sofrimento fetal','Gravidez/Parto'),
('O70','Laceração do períneo durante o parto','Gravidez/Parto'),
('O71','Outros traumatismos obstétricos','Gravidez/Parto'),
('O72','Hemorragia pós-parto','Gravidez/Parto'),('O73','Retenção da placenta e das membranas sem hemorragia','Gravidez/Parto'),
('O75','Outras complicações do trabalho de parto e do parto','Gravidez/Parto'),
('O80','Parto único espontâneo','Gravidez/Parto'),('O81','Parto por fórceps e extrator a vácuo','Gravidez/Parto'),
('O82','Parto por cesariana','Gravidez/Parto'),('O83','Outros tipos de parto único assistido','Gravidez/Parto'),
('O84','Parto múltiplo','Gravidez/Parto'),
('O85','Sepse puerperal','Gravidez/Parto'),('O86','Outras infecções puerperais','Gravidez/Parto'),
('O87','Complicações venosas no puerpério','Gravidez/Parto'),
('O88','Embolia obstétrica','Gravidez/Parto'),('O90','Complicações do puerpério','Gravidez/Parto'),
('O91','Infecções da mama associadas ao parto','Gravidez/Parto'),
('O92','Outras afecções da mama e da lactação associadas ao parto','Gravidez/Parto'),
('O95','Morte obstétrica de causa não especificada','Gravidez/Parto'),
('O96','Morte devida a qualquer causa obstétrica','Gravidez/Parto'),
('O98','Doenças infecciosas e parasitárias da mãe','Gravidez/Parto'),
('O99','Outras doenças da mãe classificadas em outra parte','Gravidez/Parto'),
-- ══ CAPÍTULO XIX — Lesões, envenenamentos (S00–T98) ══
('S00','Traumatismo superficial da cabeça','Traumatismo/Envenenamento'),
('S01','Ferimento da cabeça','Traumatismo/Envenenamento'),
('S02','Fratura do crânio e dos ossos da face','Traumatismo/Envenenamento'),
('S06','Traumatismo intracraniano','Traumatismo/Envenenamento'),
('S06.0','Concussão cerebral','Traumatismo/Envenenamento'),
('S06.1','Edema cerebral traumático','Traumatismo/Envenenamento'),
('S06.2','Traumatismo cerebral difuso','Traumatismo/Envenenamento'),
('S06.3','Traumatismo cerebral focal','Traumatismo/Envenenamento'),
('S06.4','Hemorragia epidural','Traumatismo/Envenenamento'),
('S06.5','Hemorragia subdural traumática','Traumatismo/Envenenamento'),
('S06.6','Hemorragia subaracnóidea traumática','Traumatismo/Envenenamento'),
('S09','Outros traumatismos da cabeça','Traumatismo/Envenenamento'),
('S12','Fratura da coluna cervical','Traumatismo/Envenenamento'),
('S14','Traumatismo dos nervos e da medula espinhal na coluna cervical','Traumatismo/Envenenamento'),
('S20','Traumatismo superficial do tórax','Traumatismo/Envenenamento'),
('S21','Ferimento do tórax','Traumatismo/Envenenamento'),
('S22','Fratura de costela, esterno e coluna torácica','Traumatismo/Envenenamento'),
('S25','Traumatismo dos vasos sanguíneos do tórax','Traumatismo/Envenenamento'),
('S26','Traumatismo do coração','Traumatismo/Envenenamento'),
('S27','Traumatismo de outros órgãos intratorácicos','Traumatismo/Envenenamento'),
('S29','Outros traumatismos do tórax','Traumatismo/Envenenamento'),
('S30','Traumatismo superficial do abdome, parte inferior do dorso, pelve e genitais externos','Traumatismo/Envenenamento'),
('S31','Ferimento do abdome, parte inferior do dorso, pelve e genitais externos','Traumatismo/Envenenamento'),
('S32','Fratura da coluna lombar e da pelve','Traumatismo/Envenenamento'),
('S36','Traumatismo dos órgãos intra-abdominais','Traumatismo/Envenenamento'),
('S37','Traumatismo dos órgãos pélvicos','Traumatismo/Envenenamento'),
('S39','Outros traumatismos do abdome, parte inferior do dorso, pelve e genitais externos','Traumatismo/Envenenamento'),
('S40','Traumatismo superficial do ombro e do braço','Traumatismo/Envenenamento'),
('S42','Fratura do ombro e do braço','Traumatismo/Envenenamento'),
('S50','Traumatismo superficial do antebraço','Traumatismo/Envenenamento'),
('S52','Fratura do antebraço','Traumatismo/Envenenamento'),
('S60','Traumatismo superficial do punho e da mão','Traumatismo/Envenenamento'),
('S62','Fratura ao nível do punho e da mão','Traumatismo/Envenenamento'),
('S70','Traumatismo superficial do quadril e da coxa','Traumatismo/Envenenamento'),
('S72','Fratura do fêmur','Traumatismo/Envenenamento'),
('S79','Outros traumatismos do quadril e da coxa','Traumatismo/Envenenamento'),
('S80','Traumatismo superficial da perna','Traumatismo/Envenenamento'),
('S82','Fratura da perna','Traumatismo/Envenenamento'),
('S90','Traumatismo superficial do tornozelo e do pé','Traumatismo/Envenenamento'),
('S92','Fratura do pé','Traumatismo/Envenenamento'),
('T07','Traumatismos múltiplos não especificados','Traumatismo/Envenenamento'),
('T14','Traumatismo de região não especificada do corpo','Traumatismo/Envenenamento'),
('T20','Queimadura e corrosão da cabeça e do pescoço','Traumatismo/Envenenamento'),
('T21','Queimadura e corrosão do tronco','Traumatismo/Envenenamento'),
('T22','Queimadura e corrosão do ombro e do membro superior','Traumatismo/Envenenamento'),
('T24','Queimadura e corrosão do quadril e do membro inferior','Traumatismo/Envenenamento'),
('T29','Queimaduras e corrosões de múltiplas regiões','Traumatismo/Envenenamento'),
('T30','Queimaduras de localização não especificada','Traumatismo/Envenenamento'),
('T36','Intoxicação por antibióticos sistêmicos','Traumatismo/Envenenamento'),
('T39','Intoxicação por analgésicos, antipiréticos e anti-reumáticos','Traumatismo/Envenenamento'),
('T40','Intoxicação por narcóticos e psicodislépticos','Traumatismo/Envenenamento'),
('T41','Intoxicação por anestésicos','Traumatismo/Envenenamento'),
('T42','Intoxicação por antiepilépticos, sedativos-hipnóticos','Traumatismo/Envenenamento'),
('T43','Intoxicação por substâncias psicotrópicas','Traumatismo/Envenenamento'),
('T45','Intoxicação por agentes primariamente sistêmicos e hematológicos','Traumatismo/Envenenamento'),
('T50','Intoxicação por diuréticos e outras substâncias','Traumatismo/Envenenamento'),
('T51','Efeitos tóxicos do álcool','Traumatismo/Envenenamento'),
('T56','Efeitos tóxicos de metais','Traumatismo/Envenenamento'),
('T57','Efeitos tóxicos de outras substâncias inorgânicas','Traumatismo/Envenenamento'),
('T58','Efeito tóxico do monóxido de carbono','Traumatismo/Envenenamento'),
('T59','Efeitos tóxicos de outros gases, fumaças e vapores','Traumatismo/Envenenamento'),
('T60','Efeitos tóxicos de pesticidas','Traumatismo/Envenenamento'),
('T61','Efeitos tóxicos de substâncias nocivas ingeridas como alimentos do mar','Traumatismo/Envenenamento'),
('T62','Efeitos tóxicos de outras substâncias nocivas ingeridas como alimento','Traumatismo/Envenenamento'),
('T63','Efeito tóxico de contato com animais peçonhentos','Traumatismo/Envenenamento'),
('T65','Efeitos tóxicos de outras substâncias e das não especificadas','Traumatismo/Envenenamento'),
('T66','Efeitos não especificados da radiação','Traumatismo/Envenenamento'),
('T67','Efeitos do calor e da luz','Traumatismo/Envenenamento'),
('T68','Hipotermia','Traumatismo/Envenenamento'),
('T69','Outros efeitos da temperatura reduzida','Traumatismo/Envenenamento'),
('T70','Efeitos da pressão do ar e da água','Traumatismo/Envenenamento'),
('T71','Asfixia','Traumatismo/Envenenamento'),('T73','Efeitos de outras privações','Traumatismo/Envenenamento'),
('T74','Síndromes de maus tratos','Traumatismo/Envenenamento'),
('T75','Efeitos de outras causas externas','Traumatismo/Envenenamento'),
('T78','Efeitos adversos não classificados em outra parte','Traumatismo/Envenenamento'),
('T79','Certas complicações precoces dos traumatismos','Traumatismo/Envenenamento'),
('T80','Complicações conseqüentes à infusão, transfusão e injeção terapêutica','Traumatismo/Envenenamento'),
('T81','Complicações de procedimentos','Traumatismo/Envenenamento'),
('T82','Complicações de dispositivos protéticos cardíacos e vasculares','Traumatismo/Envenenamento'),
('T83','Complicações de dispositivos protéticos geniturinários','Traumatismo/Envenenamento'),
('T84','Complicações de dispositivos protéticos ortopédicos internos','Traumatismo/Envenenamento'),
('T85','Complicações de outros dispositivos protéticos internos','Traumatismo/Envenenamento'),
('T86','Falha e rejeição de órgãos e tecidos transplantados','Traumatismo/Envenenamento'),
('T87','Complicações características dos reimplantes e amputações','Traumatismo/Envenenamento'),
('T88','Outras complicações de cuidados médicos e cirúrgicos','Traumatismo/Envenenamento'),
('T90','Sequelas de traumatismos da cabeça','Traumatismo/Envenenamento'),
('T91','Sequelas de traumatismos do pescoço e do tronco','Traumatismo/Envenenamento'),
('T92','Sequelas de traumatismos dos membros superiores','Traumatismo/Envenenamento'),
('T93','Sequelas de traumatismos dos membros inferiores','Traumatismo/Envenenamento'),
('T94','Sequelas de traumatismos de múltiplas regiões e de regiões não especificadas','Traumatismo/Envenenamento'),
('T95','Sequelas de queimaduras, corrosões e geladura','Traumatismo/Envenenamento'),
('T96','Sequelas de intoxicações por drogas, medicamentos e substâncias biológicas','Traumatismo/Envenenamento'),
('T97','Sequelas de efeitos tóxicos de substâncias de origem predominantemente não-medicinal','Traumatismo/Envenenamento'),
('T98','Sequelas de outros efeitos de causas externas','Traumatismo/Envenenamento'),
-- ══ CAPÍTULO XX — Causas externas (V01–Y98) ══
('V01','Pedestre traumatizado em colisão com bicicleta','Causas Externas'),
('V02','Pedestre traumatizado em colisão com veículo a motor de duas ou três rodas','Causas Externas'),
('V03','Pedestre traumatizado em colisão com automóvel','Causas Externas'),
('V09','Pedestre traumatizado em outros acidentes de transporte','Causas Externas'),
('V10','Ciclista traumatizado em colisão com pedestre ou animal','Causas Externas'),
('V19','Ciclista traumatizado em outros acidentes de transporte','Causas Externas'),
('V20','Motociclista traumatizado em colisão com pedestre ou animal','Causas Externas'),
('V29','Motociclista traumatizado em outros acidentes de transporte','Causas Externas'),
('V40','Ocupante de automóvel traumatizado em colisão com pedestre ou animal','Causas Externas'),
('V49','Ocupante de automóvel traumatizado em outros acidentes de transporte','Causas Externas'),
('V89','Acidente de transporte não especificado','Causas Externas'),
('W01','Queda no mesmo nível por escorregão, tropeção e passos em falso','Causas Externas'),
('W06','Queda de cama','Causas Externas'),('W07','Queda de cadeira','Causas Externas'),
('W11','Queda em e de escadas e degraus','Causas Externas'),
('W17','Outras quedas de um nível a outro','Causas Externas'),
('W19','Queda não especificada','Causas Externas'),
('W20','Impacto causado por objeto projetado, lançado ou em queda','Causas Externas'),
('W50','Golpe, mordedura, pontapé, arranhão e torsão causados por outra pessoa','Causas Externas'),
('W65','Afogamento e submersão em banheira','Causas Externas'),
('W74','Afogamento e submersão não especificados','Causas Externas'),
('X00','Exposição a fogo não controlado em edificação ou estrutura','Causas Externas'),
('X60','Auto-intoxicação por e exposição intencional a analgésicos','Causas Externas'),
('X70','Lesão autoprovocada intencionalmente por enforcamento','Causas Externas'),
('X84','Lesão autoprovocada intencionalmente por meios não especificados','Causas Externas'),
('Y00','Agressão por objeto contundente','Causas Externas'),
('Y04','Agressão por meio de força corporal','Causas Externas'),
('Y06','Negligência e abandono','Causas Externas'),
('Y09','Agressão por outros meios e meios não especificados','Causas Externas'),
('Y35','Intervenção legal','Causas Externas'),
('Y40','Efeitos adversos de antibióticos sistêmicos','Causas Externas'),
('Y43','Efeitos adversos de outras drogas sistêmicas','Causas Externas'),
('Y45','Efeitos adversos de analgésicos, antipiréticos e anti-reumáticos','Causas Externas'),
('Y50','Efeitos adversos de estimulantes do sistema nervoso central','Causas Externas'),
('Y57','Efeitos adversos de outras drogas e medicamentos','Causas Externas'),
('Y60','Corte, punção, perfuração ou hemorragia acidentais durante a prestação de cuidados médicos','Causas Externas'),
('Y83','Intervenção cirúrgica e outras operações cirúrgicas como causa de reação anormal','Causas Externas'),
('Y84','Outros procedimentos médicos como causa de reação anormal','Causas Externas'),
('Y88','Sequela de efeitos adversos de drogas, medicamentos e substâncias biológicas','Causas Externas'),
('Y89','Sequela de outras causas externas','Causas Externas'),
-- ══ CAPÍTULO XXI — Fatores que influenciam o estado de saúde (Z00–Z99) ══
('Z00','Exame geral e investigação de pessoas sem queixas','Fatores de Saúde'),
('Z01','Outros exames e investigações especiais de pessoas sem queixa','Fatores de Saúde'),
('Z02','Exame e encontro para fins administrativos','Fatores de Saúde'),
('Z03','Observação e avaliação médica por suspeita de doenças','Fatores de Saúde'),
('Z04','Exame e observação por outras razões','Fatores de Saúde'),
('Z08','Exame de acompanhamento de tratamento de neoplasia maligna','Fatores de Saúde'),
('Z09','Exame de acompanhamento após tratamento de outras condições','Fatores de Saúde'),
('Z10','Exame de saúde de rotina de populações definidas','Fatores de Saúde'),
('Z11','Exame de rastreamento especial para doenças infecciosas e parasitárias','Fatores de Saúde'),
('Z12','Exame de rastreamento especial para neoplasias','Fatores de Saúde'),
('Z13','Exame de rastreamento especial para outras doenças e transtornos','Fatores de Saúde'),
('Z20','Contato e exposição a doenças transmissíveis','Fatores de Saúde'),
('Z21','Estado de infecção assintomática pelo HIV','Fatores de Saúde'),
('Z22','Portador de doenças infecciosas','Fatores de Saúde'),
('Z23','Necessidade de imunização contra doença bacteriana isolada','Fatores de Saúde'),
('Z24','Necessidade de imunização contra certas doenças virais isoladas','Fatores de Saúde'),
('Z25','Necessidade de imunização contra outras doenças virais isoladas','Fatores de Saúde'),
('Z30','Anticoncepção','Fatores de Saúde'),('Z31','Procriação','Fatores de Saúde'),
('Z32','Exame e teste de gravidez','Fatores de Saúde'),('Z33','Estado de gravidez','Fatores de Saúde'),
('Z34','Supervisão de gravidez normal','Fatores de Saúde'),
('Z35','Supervisão de gravidez de alto risco','Fatores de Saúde'),
('Z36','Exame para rastreamento pré-natal','Fatores de Saúde'),
('Z37','Resultado do parto','Fatores de Saúde'),('Z38','Neonatos vivos segundo o local de nascimento','Fatores de Saúde'),
('Z39','Exame e cuidados do pós-parto','Fatores de Saúde'),
('Z40','Cirurgia profilática','Fatores de Saúde'),('Z41','Procedimentos para outros fins que não a melhora do estado de saúde','Fatores de Saúde'),
('Z42','Acompanhamento de cirurgia plástica','Fatores de Saúde'),
('Z43','Atenção a orifícios artificiais','Fatores de Saúde'),
('Z44','Adaptação de próteses externas','Fatores de Saúde'),
('Z45','Adaptação e manuseio de dispositivo implantado','Fatores de Saúde'),
('Z46','Adaptação e manuseio de outros dispositivos','Fatores de Saúde'),
('Z47','Outros cuidados de acompanhamento ortopédico','Fatores de Saúde'),
('Z48','Outros cuidados de acompanhamento cirúrgico','Fatores de Saúde'),
('Z49','Cuidados envolvendo diálise','Fatores de Saúde'),
('Z50','Cuidados envolvendo o uso de procedimentos de reabilitação','Fatores de Saúde'),
('Z51','Outros cuidados médicos','Fatores de Saúde'),
('Z52','Doadores de órgãos e tecidos','Fatores de Saúde'),
('Z53','Pessoas que entram em contato com serviços de saúde por procedimentos específicos','Fatores de Saúde'),
('Z54','Convalescença','Fatores de Saúde'),
('Z55','Problemas relacionados com a educação e com a instrução','Fatores de Saúde'),
('Z56','Problemas relacionados com o emprego e o desemprego','Fatores de Saúde'),
('Z57','Exposição ocupacional a fatores de risco','Fatores de Saúde'),
('Z58','Problemas relacionados com o ambiente físico','Fatores de Saúde'),
('Z59','Problemas relacionados com a habitação e com as condições econômicas','Fatores de Saúde'),
('Z60','Problemas relacionados com o ambiente social','Fatores de Saúde'),
('Z61','Problemas relacionados com eventos negativos de vida na infância','Fatores de Saúde'),
('Z62','Outros problemas relacionados com a criação','Fatores de Saúde'),
('Z63','Outros problemas relacionados com o grupo primário de apoio','Fatores de Saúde'),
('Z64','Problemas relacionados com certas circunstâncias psicossociais','Fatores de Saúde'),
('Z65','Problemas relacionados com outras circunstâncias psicossociais','Fatores de Saúde'),
('Z70','Consulta relacionada com atitudes, comportamentos e orientação sexuais','Fatores de Saúde'),
('Z71','Pessoas em contato com os serviços de saúde para outros fins de consulta','Fatores de Saúde'),
('Z72','Problemas relacionados com o estilo de vida','Fatores de Saúde'),
('Z73','Problemas relacionados com a organização de seu modo de vida','Fatores de Saúde'),
('Z74','Problemas relacionados com a dependência do prestador de cuidados','Fatores de Saúde'),
('Z75','Problemas relacionados com as instalações médicas e outros serviços de saúde','Fatores de Saúde'),
('Z76','Pessoas em contato com os serviços de saúde em outras circunstâncias','Fatores de Saúde'),
('Z80','História familiar de neoplasias malignas','Fatores de Saúde'),
('Z81','História familiar de transtornos mentais e comportamentais','Fatores de Saúde'),
('Z82','História familiar de determinadas incapacidades e doenças crônicas','Fatores de Saúde'),
('Z83','História familiar de outras afecções específicas','Fatores de Saúde'),
('Z84','História familiar de outras condições','Fatores de Saúde'),
('Z85','História pessoal de neoplasias malignas','Fatores de Saúde'),
('Z86','História pessoal de certas outras doenças','Fatores de Saúde'),
('Z87','História pessoal de outras doenças e afecções','Fatores de Saúde'),
('Z88','História pessoal de alergia a drogas','Fatores de Saúde'),
('Z89','Ausência adquirida de membro','Fatores de Saúde'),
('Z90','Ausência adquirida de órgão','Fatores de Saúde'),
('Z91','História pessoal de fatores de risco','Fatores de Saúde'),
('Z92','História pessoal de tratamento médico','Fatores de Saúde'),
('Z93','Orifícios artificiais','Fatores de Saúde'),
('Z94','Órgão e tecido transplantados','Fatores de Saúde'),
('Z95','Presença de implantes e enxertos cardíacos e vasculares','Fatores de Saúde'),
('Z96','Presença de outros implantes funcionais','Fatores de Saúde'),
('Z97','Presença de outros dispositivos','Fatores de Saúde'),
('Z98','Outros estados pós-cirúrgicos','Fatores de Saúde'),
('Z99','Dependência de máquinas e dispositivos capacitantes','Fatores de Saúde')
ON CONFLICT (code) DO UPDATE SET
  description = EXCLUDED.description,
  category = EXCLUDED.category;
